language: csharp
solution: ./ShopService/ShopService.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - nuget restore ./ShopService/ShopService.sln
  - nuget install NUnit.Runners -Version 3.5 -OutputDirectory testrunner
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script